[platformio]
default_envs = esp32c6

[env:esp32c6]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags =
    -DSSD1306_WIDTH=128
    -DSSD1306_HEIGHT=64
    -DWAVE_OUTPUT_GPIO=4
    -DROTARY_ENCODER_A_GPIO=8
    -DROTARY_ENCODER_B_GPIO=9
    -DROTARY_ENCODER_BUTTON_GPIO=10
lib_deps =
    
